name: Build and deploy site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional build steps can be added here (Node/Tailwind build). If you build to a folder
      # like `dist`, change the `path` in the upload step below to `./dist`.

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
